name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: yeikel/setup-java@cache/mvn-wrapper
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        env:
          MVNW_VERBOSE: "true"
        run: ./mvnw verify
